### ISSUE TITLE
coordinates from wkt2geojson() are not numeric

### ISSUE THREAD

**Issue by pieterprovoost** [ropensci/wellknown#14]
Coordinates from wkt2geojson() are character instead of numeric, which causes problems when using the results with `leaflet`.

```R
str <- "POLYGON ((100 0.1, 101.1 0.3, 101 0.5, 100 0.1),(103.2 0.2, 104.8 0.2, 100.8 0.8, 103.2 0.2))"
as_json(wkt2geojson(str))
```

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        ["100.0000000000000000", "0.1000000000000000"],
        ["101.0999999999999943", "0.3000000000000000"],
        ["101.0000000000000000", "0.5000000000000000"],
        ["100.0000000000000000", "0.1000000000000000"]
      ],
      [
        ["103.2000000000000028", "0.2000000000000000"],
        ["104.7999999999999972", "0.2000000000000000"],
        ["100.7999999999999972", "0.8000000000000000"],
        ["103.2000000000000028", "0.2000000000000000"]
      ]
    ]
  }
} 
```

**Comment by sckott** [comment]
Thanks for the issue - Do you mean specifically with the R package `leaflet`?

**Comment by sckott** [comment]
The problem is that if we use numeric class values the digits after the decimal will be lost down to the default setting for digits in R. I've played around with messing with the digits setting in the user's R session, but I'm concerned about doing so as that could affect other things they are doing - I do agree that it would be best if they were not character class

**Comment by pieterprovoost** [comment]
My problem is specifically with the `leaflet` package, but this seems like a general issue as coordinates should be numbers according to the geojson spec.

Maybe make it optional?

**Comment by sckott** [comment]
Right, we should follow the spec, i'll see about changing it

**Comment by sckott** [comment]
@pieterprovoost okay, reinstall, then e.g., try

```r
library("wellknown")
library("leaflet")
str <- "POLYGON ((100 0.1, 101.1 0.3, 101 0.5, 100 0.1),(103.2 0.2, 104.8 0.2, 100.8 0.8, 103.2 0.2))"
geoj <- wkt2geojson(str) %>% properties(style=list(color = "red"))
cent <- get_centroid(geoj)
leaflet() %>% 
  addTiles() %>% 
  addGeoJSON(as_json(geoj)) %>% 
  setView(lng = cent[1], lat = cent[2], zoom = 6)
```

![pic](http://f.cl.ly/items/3Q1O1e1T1R0a2y0V1f1D/Screen%20Shot%202016-02-10%20at%2011.01.44%20AM.png)

**Comment by pieterprovoost** [comment]
Works great, thanks!

**Comment by sckott** [comment]
great, the other thing I did in that eg is that leaflet expects the geojson to have a `properties` element, and the geojson made with `wkt2geojson()` doesn't have a properties element by default, that little helper function `properties()` adds them
