### ISSUE TITLE
Case sensitivity in wkt2geojson()

### ISSUE THREAD

**Issue by pachevalier** [ropensci/wellknown#16]
Sometimes WKT objects are written in lower case. However `wkt2geojson` only works with uppercase. Is there any reason for that ?

```
str <- "POINT (-116.4000000000000057 45.2000000000000028)"
wkt2geojson(str)
```

gives a result, but : 

```
str <- "Point (-116.4000000000000057 45.2000000000000028)"
 wkt2geojson(str)
```

returns an error message.

**Comment by sckott** [comment]
thanks for the report, just didn't think about case - will fix, thanks!

**Comment by sckott** [comment]
@pachevalier can you reinstall `devtools::install_github("ropensci/wellknown")` and try again

**Comment by sckott** [comment]
sorted, closing
