### ISSUE TITLE
Compilation errors with release candidate for BH package 1.75.0

### ISSUE THREAD

**Issue by eddelbuettel** [ropensci/wellknown#33]
As mentioned [in issue 76 at the BH repo](https://github.com/eddelbuettel/bh/issues/76), its new version creates compilation issues with package `wellknown`. I have not had time to really dive into this, but this may be caused by changes to Boost geometry---which also required a switch to C++14 for a few other packages.  Here it is less clear but _something_ changed with the definition of `point`.

Please reach out if you have any questions, and a big Thank You! for maintaining `wellknown` on CRAN.

(Sorry about the copy-and-paste error on the initial title. This was issue five of five I had to file and this slipped. My bad.)

**Comment by sckott** [comment]
Thanks for the issue. Looking into it

**Comment by eddelbuettel** [comment]
Any news, by chance? Do you think you may have an updated version by early January?

**Comment by sckott** [comment]
Was on break. I'll get a new version to CRAN soon

**Comment by eddelbuettel** [comment]
We're all set: wellknown on CRAN, as is BH now.  Thanks again.
