### ISSUE TITLE
boost error on CRAN checks

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/wellknown#36]
I think the issue found on 
https://cran.r-project.org/web/checks/check_results_wellknown.html

is related to this
https://github.com/eddelbuettel/bh/issues/83

**Comment by jhnwllr** [comment]
This seems like a CRAN c++ compiler issue. Not sure if anything can even be done. @sckott

**Comment by jhnwllr** [comment]
Yes I was thinking about that since rgbif only uses one function (I think). 

I might still try to rescue it to give some time to the other people using the package. I was also interested in getting more familiar with Rcpp. I will maybe start migrating to wk. 

Thanks for your input.

**Comment by sckott** [comment]
yeah, def if interested in learning Rcpp more this is a good opportunity. A newer pkg alternative is https://cpp11.r-lib.org/ which may be worth taking a look at

**Comment by jhnwllr** [comment]
I have decided to move rgbif to wk. I don't think I will be able to fix the issue before the package gets archived on CRAN.

**Comment by salvafern** [comment]
I am afraid I cannot provide much help, both short on knowledge about C++ and time. I will move mregions to wk. But thanks a lot for checking this out! I will follow this issue closely.

**Comment by maelle** [comment]
@sckott has requested archival of this package on CRAN.
