### ISSUE TITLE
wkt validator

### ISSUE THREAD

**Issue by sckott** [ropensci/wellknown#9]
No good solution right now for validating wkt strings. Could use geos C library, but way to heavy just for validating. There doesn't seem to be any  web APIs for this. The Python client `geomet` simply throws an error if the string doesn't parse. 

Could work on a R validator - then reimplement in C if super slow.

**Comment by sckott** [comment]
WKT spec 

http://cl.ly/aFKD/download/06-103r4_Implementation_Specification_for_Geographic_Information_-_Simple_feature_access_-_Part_1_Common_Architecture_v1.2.1%20(1).pdf

**Comment by raymondben** [comment]
Some possible WKT validation errors (I am not super-familiar with the WKT spec, so don't know if these should be failing or not). They are all to do with extra whitespaces:

The starting point, which validates as TRUE:
wellknown::lint("POLYGON((154 -43.74, 154 -9, 112.9 -9, 112.9 -43.74, 154 -43.74))")

## whitespace before commas
wellknown::lint("POLYGON((154 -43.74 , 154 -9, 112.9 -9, 112.9 -43.74, 154 -43.74))")

## whitespace after ((
wellknown::lint("POLYGON(( 154 -43.74, 154 -9, 112.9 -9, 112.9 -43.74, 154 -43.74))")

## whitespace before ))
wellknown::lint("POLYGON((154 -43.74, 154 -9, 112.9 -9, 112.9 -43.74, 154 -43.74  ))")

These all fail validation.

**Comment by sckott** [comment]
thanks, i'll have a look

**Comment by sckott** [comment]
okay, try reinstalling, should work now. `devtools::install_github("ropensci/wellknown")`

**Comment by raymondben** [comment]
Yup, those pass now. Thanks

**Comment by sckott** [comment]
great!

**Comment by sckott** [comment]
@raymondben keep in mind that this wkt linter is just R regex, so it is lightweight, and avoids requiring GDAL/GEOS - thanks for helping make it better
